### PR TITLE
Typos fix in Quickstart

### PR DESCRIPTION
**Pull request by ruudud**
Yey, my first pull request!

### CODE REVIEW

**Comment by daltonmatos** [comment]
Hi, Thanks for you contributions! 
Just one question. Any reason for changing from:
      from pyroutes.utils import devserver
      devserver(application)

to

```
from pyroutes import utils
utils.devserver(application)
```

?

Anyway, +1 for this merge.

**Comment by ruudud** [comment]
Yes, consistency with the next following example, so that people following it line by line do not have to change the import. :-)

**Comment by daltonmatos** [comment]
Great! Fair enough. Let's wait Klette to make the merge.

**Comment by klette** [comment]
Please use the pyroutes-organisation repositories. Mine are a bit dated. The docs have been moved to a different repo - please apply patch and merge into https://github.com/pyroutes/pyroutes.github.com

**Pull request closed without merging**
